// ── Cold email landing page — appealthedenial.com/hello ──────────────────────
import { useState } from "react";

const BENEFITS = [
  {
    title: "Formal appeal letters",
    desc: "Citing specific federal statutes — written by us, not generated by a template tool.",
  },
  {
    title: "Direct filing",
    desc: "We send via certified mail or fax, creating a legal paper trail on the patient's behalf.",
  },
  {
    title: "External review escalation",
    desc: "If the insurer denies again, we escalate to independent external review automatically.",
  },
  {
    title: "Zero staff time required",
    desc: "Your team forwards the denial — we handle everything else, no check-ins needed.",
  },
  {
    title: "All denial types covered",
    desc: "Medical necessity, prior auth, out-of-network, billing errors, late filing, and more.",
  },
  {
    title: "Patient communication included",
    desc: "We keep patients updated so your front desk isn't fielding calls about claim status.",
  },
];

const STEPS = [
  {
    step: "01",
    title: "Forward us the denial",
    desc: "Share the denial notice and supporting documentation. Takes about 2 minutes.",
  },
  {
    step: "02",
    title: "We build & file the appeal",
    desc: "We identify the strongest legal and clinical arguments and file directly with the insurer.",
  },
  {
    step: "03",
    title: "We follow it through",
    desc: "We track the response, escalate if needed, and keep the patient informed — your staff hears nothing until it's resolved.",
  },
];

export default function OutreachLanding({ navigate }) {
  const [form, setForm]     = useState({ name: "", email: "" });
  const [status, setStatus] = useState("idle"); // idle | sending | done | error

  async function handleSubmit(e) {
    e.preventDefault();
    setStatus("sending");
    try {
      const res = await fetch("https://formsubmit.co/ajax/will@solognecourtholdings.com", {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify({
          name:  form.name,
          email: form.email,
          _subject: "New lead from AppealTheDenial.com/hello",
          _captcha: "false",
        }),
      });
      if (res.ok) setStatus("done");
      else setStatus("error");
    } catch {
      setStatus("error");
    }
  }

  // ── Inline style tokens ──────────────────────────────────────────────────────
  const bg       = "#FFFFFF";
  const bg2      = "#F8FAFC";
  const card     = "#FFFFFF";
  const border   = "#E2E8F0";
  const blue     = "#10b981";
  const blueGlow = "#10b98150";
  const textHi   = "#0F172A";
  const textLow  = "#64748B";

  return (
    <div style={{ fontFamily: "'DM Sans', sans-serif", background: bg, minHeight: "100vh", color: textHi }}>

      {/* ── Nav ──────────────────────────────────────────────────────────────── */}
      <nav className="mob-nav" style={{
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "20px 40px", borderBottom: `1px solid ${border}`,
        position: "sticky", top: 0, zIndex: 10,
        background: "rgba(255,255,255,0.85)", backdropFilter: "blur(12px)",
      }}>
        <div style={{ fontSize: 15, fontWeight: 700, letterSpacing: -0.3, color: textHi }}>
          Appeal<span style={{ color: blue }}>TheDenial</span>
        </div>
        <button
          onClick={() => navigate("/patients")}
          className="mob-hide"
          style={{
            background: "transparent", border: `1px solid ${border}`,
            color: textLow, borderRadius: 8, padding: "8px 16px",
            fontSize: 14, cursor: "pointer", fontFamily: "inherit",
          }}
          onMouseEnter={e => { e.currentTarget.style.borderColor = blue; e.currentTarget.style.color = textHi; }}
          onMouseLeave={e => { e.currentTarget.style.borderColor = border; e.currentTarget.style.color = textLow; }}
        >
          For patients
        </button>
      </nav>

      {/* ── Hero (form front-and-center) ─────────────────────────────────────── */}
      <section className="mob-hero" style={{ maxWidth: 1140, margin: "0 auto", padding: "88px 24px 96px" }}>
       <div style={{ display: "flex", flexWrap: "wrap", gap: 56, alignItems: "center", justifyContent: "center" }}>

        {/* Left — copy */}
        <div style={{ flex: "1 1 440px", maxWidth: 600 }}>
          <div style={{
            display: "inline-block",
            background: "#10b9811a", color: blue,
            border: `1px solid #10b9813a`,
            borderRadius: 100, padding: "5px 16px",
            fontSize: 12, fontWeight: 600, letterSpacing: 1,
            textTransform: "uppercase", marginBottom: 24,
          }}>
            For practice managers &amp; office admins
          </div>

          <h1 style={{
            fontSize: "clamp(40px, 5.4vw, 66px)",
            fontWeight: 700, lineHeight: 1.04,
            letterSpacing: -2.5, marginBottom: 24, color: textHi,
          }}>
            Your staff shouldn't be{" "}
            <span style={{ color: blue }}>fighting insurance denials.</span>
          </h1>

          <p style={{
            fontSize: "clamp(17px, 1.7vw, 21px)",
            color: textLow, lineHeight: 1.6,
            maxWidth: 520,
          }}>
            We handle the entire appeals process for your patients — writing, filing, and following up — so your team can focus on care, not paperwork.
          </p>
        </div>

        {/* Right — form */}
        <div style={{ flex: "0 1 440px", width: "100%", maxWidth: 440 }}>
        <div style={{
          background: card, border: `1px solid ${border}`,
          borderRadius: 18, padding: "28px 24px",
          boxShadow: "0 10px 40px rgba(15,23,42,0.06), 0 2px 8px rgba(15,23,42,0.04)",
          textAlign: "left",
        }}>
          {status === "done" ? (
            <div style={{ textAlign: "center", padding: "12px 0" }}>
              <div style={{ fontSize: 32, marginBottom: 12, color: "#059669" }}>✓</div>
              <div style={{ fontSize: 18, fontWeight: 600, color: textHi, marginBottom: 8 }}>You're on our list.</div>
              <p style={{ fontSize: 14, color: textLow }}>We'll be in touch within one business day.</p>
            </div>
          ) : (
            <>
              <div style={{ fontSize: 16, fontWeight: 700, color: textHi, marginBottom: 4, textAlign: "center" }}>
                Get started in 30 seconds.
              </div>
              <p style={{ fontSize: 13, color: textLow, marginBottom: 20, textAlign: "center" }}>
                Drop your info and we'll reach out within one business day.
              </p>
              <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                <input
                  type="text"
                  placeholder="Your name"
                  required
                  value={form.name}
                  onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
                  style={{
                    background: bg, border: `1px solid ${border}`,
                    borderRadius: 10, padding: "14px 16px",
                    fontSize: 15, color: textHi, fontFamily: "inherit", outline: "none",
                  }}
                  onFocus={e => { e.target.style.borderColor = blue; }}
                  onBlur={e => { e.target.style.borderColor = border; }}
                />
                <input
                  type="email"
                  placeholder="Work email"
                  required
                  value={form.email}
                  onChange={e => setForm(f => ({ ...f, email: e.target.value }))}
                  style={{
                    background: bg, border: `1px solid ${border}`,
                    borderRadius: 10, padding: "14px 16px",
                    fontSize: 15, color: textHi, fontFamily: "inherit", outline: "none",
                  }}
                  onFocus={e => { e.target.style.borderColor = blue; }}
                  onBlur={e => { e.target.style.borderColor = border; }}
                />
                <button
                  type="submit"
                  disabled={status === "sending"}
                  style={{
                    background: blue, color: "#fff", border: "none",
                    borderRadius: 10, padding: "16px",
                    fontSize: 16, fontWeight: 600, cursor: status === "sending" ? "wait" : "pointer",
                    fontFamily: "inherit", letterSpacing: -0.2, width: "100%",
                    boxShadow: `0 0 30px ${blueGlow}`,
                    opacity: status === "sending" ? 0.7 : 1,
                  }}
                >
                  {status === "sending" ? "Sending…" : "Get in touch →"}
                </button>
                {status === "error" && (
                  <p style={{ fontSize: 13, color: "#f87171", margin: 0, textAlign: "center" }}>
                    Something went wrong — email us at will@solognecourtholdings.com
                  </p>
                )}
              </form>
            </>
          )}
        </div>
        <p style={{ fontSize: 12, color: textLow, marginTop: 16, textAlign: "center" }}>
          No commitment · We reply within one business day
        </p>
        </div>

       </div>
      </section>

      {/* ── How it works ─────────────────────────────────────────────────────── */}
      <section style={{ background: bg2, borderTop: `1px solid ${border}`, borderBottom: `1px solid ${border}` }}>
        <div className="mob-sec" style={{ maxWidth: 900, margin: "0 auto", padding: "80px 24px" }}>
          <div style={{ textAlign: "center", marginBottom: 48 }}>
            <div style={{ fontSize: 12, fontWeight: 600, letterSpacing: 3, textTransform: "uppercase", color: blue, marginBottom: 12 }}>
              How it works
            </div>
            <h2 style={{ fontSize: "clamp(26px, 4vw, 38px)", fontWeight: 700, letterSpacing: -1, color: textHi }}>
              You refer it. We handle it.
            </h2>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 20 }}>
            {STEPS.map(s => (
              <div key={s.step} style={{ background: card, border: `1px solid ${border}`, borderRadius: 16, padding: "28px 24px" }}>
                <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2, color: blue, marginBottom: 16, textTransform: "uppercase" }}>
                  Step {s.step}
                </div>
                <div style={{ fontSize: 17, fontWeight: 600, color: textHi, marginBottom: 10, lineHeight: 1.3 }}>{s.title}</div>
                <p style={{ fontSize: 14, color: textLow, lineHeight: 1.7 }}>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Benefits ─────────────────────────────────────────────────────────── */}
      <section className="mob-sec" style={{ maxWidth: 900, margin: "0 auto", padding: "80px 24px" }}>
        <div style={{ textAlign: "center", marginBottom: 48 }}>
          <div style={{ fontSize: 12, fontWeight: 600, letterSpacing: 3, textTransform: "uppercase", color: blue, marginBottom: 12 }}>
            What you get
          </div>
          <h2 style={{ fontSize: "clamp(24px, 3vw, 34px)", fontWeight: 700, letterSpacing: -0.5, color: textHi }}>
            Everything handled on our end.
          </h2>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 16 }}>
          {BENEFITS.map(b => (
            <div key={b.title} style={{
              background: card, border: `1px solid ${border}`,
              borderRadius: 14, padding: "22px 20px",
              display: "flex", gap: 14, alignItems: "flex-start",
            }}>
              {/* check icon */}
              <div style={{
                width: 22, height: 22, borderRadius: "50%",
                background: "#d1fae5", flexShrink: 0, marginTop: 2,
                display: "flex", alignItems: "center", justifyContent: "center",
              }}>
                <svg width="11" height="11" viewBox="0 0 12 12" fill="none">
                  <path d="M2 6l3 3 5-5" stroke="#059669" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </div>
              <div>
                <div style={{ fontSize: 15, fontWeight: 600, color: textHi, marginBottom: 6 }}>{b.title}</div>
                <p style={{ fontSize: 13, color: textLow, lineHeight: 1.6 }}>{b.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Footer ───────────────────────────────────────────────────────────── */}
      <footer className="mob-nav" style={{
        borderTop: `1px solid ${border}`, padding: "28px 40px",
        display: "flex", alignItems: "center", justifyContent: "space-between",
        flexWrap: "wrap", gap: 12,
      }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: textHi }}>
          Appeal<span style={{ color: blue }}>TheDenial</span>
        </div>
        <button
          onClick={() => navigate("/providers")}
          style={{ background: "none", border: "none", cursor: "pointer", fontSize: 13, color: "#94A3B8", fontFamily: "inherit" }}
        >
          For providers →
        </button>
        <button
          onClick={() => navigate("/patients")}
          style={{ background: "none", border: "none", cursor: "pointer", fontSize: 13, color: "#94A3B8", fontFamily: "inherit" }}
        >
          For patients →
        </button>
      </footer>

    </div>
  );
}
